spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.197.66:3306/asset-manage?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ls521314..
  redis:
    host: localhost
    port: 6379
    password: redis
    database: 1